### ISSUE TITLE
having package in dependencies breaks tests

### ISSUE THREAD

**Issue by Skytrobb** [deanhet/react-native-text-ticker#41]
I'm using jest to run my unit tests and I get these errors whenever I'm running my tests. It prevents me from building. So far the only solution I've found is uninstalling the dependency entirely, I'd prefer to avoid this if possible.
`ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at Object.get Animated [as Animated] (node_modules/react-native/Libraries/react-native/react-native-implementation.js:205:12)
      at new TextMarquee (node_modules/react-native-text-ticker/index.js:57:44)
      at constructClassInstance (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3017:22)
      at updateClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6051:9)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6829:20)
`

**Comment by deanhet** [comment]
Can you give me the test that's failing? Or even better, a small repo that reproduces the error. Initially, this looks like more of a configuration error on your end but I'd be happy to check it out and fix it if I can replicate it.

**Comment by Skytrobb** [comment]
I discovered it was a problem with my snapshot tests. shallow rendering a
few components that interacted with the text ticker seemed to do the trick.
thanks for offering to help though! we're using the ticker in our project
now and it's working smoothly
